# Source: https://forum.arduino.cc/t/getting-a-neato-xv-11-lidar-working-on-the-q/1445568/18
services:
  joystick:
    # App Lab will automatically look for the Dockerfile in the same folder
    build:
      context: .

    develop:
      # Configure `docker compose watch` to automatically rebuild the container when image source files are modified.
      # See: https://docs.docker.com/compose/how-tos/file-watch/
      watch:
        - action: rebuild
          path: ./app
        - action: rebuild
          path: brick_compose.yaml
        - action: rebuild
          path: Dockerfile
        - action: restart
          path: __init__.py

    privileged: true

    # --- ADDED FOR BLUETOOTH SUPPORT ---
    #network_mode: "host"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/input:/dev/input:ro  # Mounts input directory dynamically as Read-Only
    # -----------------------------------
    
    group_add:
      - "995"

    devices:
      #- "/dev/input:/dev/input"
      - "/usr/sbin/rfkill:/usr/sbin/rfkill" # Added to support 'rfkill unblock bluetooth' inside the script
    
    ports:
      # Expose the port for communication with the container's Flask web application.
      # See: https://docs.docker.com/reference/compose-file/services/#ports
      - "5000:5000"